const $=s=>document.querySelector(s);let selected=null,lastDetail=null;const colors=['#79d7b0','#e6b85c','#75a9e8','#f17b74','#bd8ee8','#ef9f62'];
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=0)=>v==null?'—':Number(v).toFixed(d);const pct=v=>v==null?'—':`${(100*v).toFixed(0)}%`;
async function api(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error((await r.json()).error||r.statusText);return r.json()}
async function loadList(){const data=await api('/api/experiments');const sel=$('#experimentSelect'),prior=selected;sel.innerHTML=data.experiments.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');selected=(prior&&data.experiments.some(x=>x.id===prior))?prior:data.experiments[0]?.id;sel.value=selected||'';if(selected)await loadDetail()}
async function loadDetail(){try{lastDetail=await api(`/api/experiment?id=${encodeURIComponent(selected)}`);render(lastDetail);$('#refreshStatus').textContent=`Updated ${new Date().toLocaleTimeString()}`;$('#pulse').style.background='#79d7b0'}catch(e){$('#refreshStatus').textContent=e.message;$('#pulse').style.background='#f17b74'}}
function card(label,value,sub=''){return `<div class="card"><span class="eyebrow">${esc(label)}</span><div class="value">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`}
function render(d){const t=$('#dashboardTemplate').content.cloneNode(true);$('#content').replaceChildren(t);const m=d.manifest,s=d.summary,r=d.runs,rounds=m.rounds||s.configured_rounds;const completed=s.next_round??d.checkpoint.next_round??0;$('#experimentMeta').innerHTML=`<strong>${esc(d.kind)}</strong><br>${esc(m.model||(m.models||[]).join(', '))}<br>${esc((m.conditions||[]).join(' · '))}<br>seed: ${esc(m.experiment_seed)}`;const scores=r.map(x=>x.score).filter(x=>x!=null),floors=r.map(x=>x.floors).filter(x=>x!=null);$('#cards').innerHTML=card('PROGRESS',rounds?`${completed}/${rounds}`:`${r.length} runs`,'completed rounds')+card('RUNS',r.length,s.interrupted?'interrupted':'recorded')+card('MEAN SCORE',scores.length?n(scores.reduce((a,b)=>a+b,0)/scores.length,1):'—','all recorded runs')+card('BEST DEPTH',floors.length?Math.max(...floors):'—','floors completed')+card('MESSAGES',(d.chat||[]).length,'public posts');renderChart(r);renderLatest(r);renderWarnings(d);renderBranches(d);renderChat(d.chat||[]);renderRuns(r);renderReviews(d.reviews||[])}
function seriesKey(x){return `${x.condition||'run'} / ${x.guest||x.identity?.agent_id||'agent'}`}
function renderChart(runs){const social=runs.filter(x=>x.round!=null&&x.score!=null);const groups={};social.forEach(x=>(groups[seriesKey(x)]??=[]).push(x));const keys=Object.keys(groups);$('#legend').innerHTML=keys.map((k,i)=>`<span><i class="swatch" style="background:${colors[i%colors.length]}"></i>${esc(k)}</span>`).join('');requestAnimationFrame(()=>{const c=$('#scoreChart'),ctx=c.getContext('2d'),ratio=devicePixelRatio||1,w=c.clientWidth,h=250;c.width=w*ratio;c.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const vals=social.map(x=>x.score),max=Math.max(1,...vals),maxRound=Math.max(1,...social.map(x=>x.round));ctx.strokeStyle='#26343d';ctx.fillStyle='#91a09b';ctx.font='10px monospace';for(let i=0;i<=4;i++){let y=15+(h-35)*i/4;ctx.beginPath();ctx.moveTo(42,y);ctx.lineTo(w-8,y);ctx.stroke();ctx.fillText(Math.round(max*(1-i/4)),4,y+3)}keys.forEach((k,i)=>{const pts=groups[k].sort((a,b)=>a.round-b.round);ctx.strokeStyle=colors[i%colors.length];ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();pts.forEach((p,j)=>{let x=45+(w-58)*(p.round/maxRound),y=15+(h-35)*(1-p.score/max);j?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillRect(x-2,y-2,4,4)});ctx.stroke()})})}
function renderLatest(runs){if(!runs.length){$('#latestRuns').innerHTML='<p class="quiet">No runs yet.</p>';return}const round=Math.max(...runs.map(x=>x.round??-1)),latest=runs.filter(x=>(x.round??-1)===round);$('#latestRuns').innerHTML=latest.map(x=>`<div class="run-row"><strong>${esc(x.condition)} / ${esc(x.guest)}</strong><span class="pill">score ${esc(x.score)}</span><span class="pill">floors ${esc(x.floors)}</span><span class="pill">turns ${esc(x.turns)}</span><span class="pill">${esc(x.final_branch||'linear')}</span></div>`).join('')}
function renderWarnings(d){const warnings=[];(d.reviews||[]).filter(x=>x.error).forEach(x=>warnings.push(`Round ${(x.round??0)+1}, ${x.condition}/${x.guest}: ${x.error}`));(d.runs||[]).filter(x=>x.cause&&String(x.cause).includes('malformed')).forEach(x=>warnings.push(`${x.condition}/${x.guest}: ${x.cause}`));if(d.summary?.interrupted)warnings.push('Experiment is marked interrupted; it can be resumed.');$('#warnings').innerHTML=warnings.length?warnings.map(x=>`<div class="warning">${esc(x)}</div>`).join(''):'<p class="good">No recorded review or protocol failures.</p>'}
function renderBranches(d){const runs=d.runs.filter(x=>x.final_branch);if(!runs.length){$('#branches').innerHTML='<p class="quiet">No branch-aware runs recorded yet.</p>';return}const by={};runs.forEach(x=>{const k=x.final_branch||'root';by[k]=(by[k]||0)+1});const counts=Object.entries(by).sort((a,b)=>b[1]-a[1]);const choices=runs.flatMap(x=>x.branch_choices||[]),a=choices.filter(x=>x==='A').length,b=choices.filter(x=>x==='B').length;$('#branches').innerHTML=`<p class="quiet">Exit choices: A ${a} · B ${b} · ${counts.length} distinct terminal addresses</p><div class="branch-grid">${counts.slice(0,20).map(([path,count])=>`<div class="branch-card"><div class="branch-address">${esc(path)}</div><div class="quiet">${count} run${count===1?'':'s'}</div></div>`).join('')}</div>`}
function renderChat(chat){$('#chat').innerHTML=chat.length?chat.map(x=>`<div class="chat-message"><div class="who">ROUND ${(x.round??0)+1} · ${esc(x.author)} · ${esc(x.characters??String(x.message||'').length)} chars</div><p>${esc(x.message)}</p></div>`).join(''):'<p class="quiet">The room is silent.</p>'}
function renderRuns(runs){const h=['Round','Condition','Guest','Score','Floors','Turns','Branch','Retrace','Zero-fog','Latency'];$('#runsTable').innerHTML=`<thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${runs.map(x=>`<tr><td>${x.round==null?'—':x.round+1}</td><td>${esc(x.condition)}</td><td>${esc(x.guest)}</td><td>${esc(x.score)}</td><td>${esc(x.floors)}</td><td>${esc(x.turns)}</td><td>${esc(x.final_branch)}</td><td>${pct(x.retrace_rate)}</td><td>${esc(x.zero_fog_turns)}</td><td>${x.mean_latency==null?'—':n(x.mean_latency,1)+'s'}</td></tr>`).join('')}</tbody>`}
function renderReviews(rows){$('#reviews').innerHTML=rows.length?rows.slice().reverse().map(x=>`<details><summary>Round ${(x.round??0)+1} · ${esc(x.condition)}/${esc(x.guest)} ${x.error?'· ERROR':''}</summary>${x.error?`<p class="bad">${esc(x.error)}</p>`:''}<p>${esc(x.reflection)}</p><pre>Notebook: ${esc(x.notebook)}\nPublic: ${esc(x.public_message)}${x.thinking?'\nThinking: '+esc(x.thinking):''}</pre></details>`).join(''):'<p class="quiet">No reviews recorded.</p>'}
$('#experimentSelect').addEventListener('change',e=>{selected=e.target.value;loadDetail()});$('#refreshButton').addEventListener('click',()=>loadList());setInterval(()=>{if($('#autoRefresh').checked)loadList()},5000);loadList();
